"""empty message

Revision ID: 33b0ef08b33d
Revises: 60fdf2bfde5d
Create Date: 2025-03-30 21:02:16.150008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33b0ef08b33d'
down_revision = '60fdf2bfde5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
